//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlibanhang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSanpham
    {
        public string maSP { get; set; }
        public string tenSP { get; set; }
        public Nullable<int> gia { get; set; }
        public Nullable<int> soluong { get; set; }
    }
}
